// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVM1BEEN3TX1fNkuJ_5qCwyhuKaC-NWpc',
    appId: '1:631873486595:web:46175467bcfd84e960f336',
    messagingSenderId: '631873486595',
    projectId: 'week1-firebas',
    authDomain: 'week1-firebas.firebaseapp.com',
    storageBucket: 'week1-firebas.firebasestorage.app',
    measurementId: 'G-HMYD0QSN3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD3pwRJjbhgr4Zr1F4igClnr-W08_Qfxs',
    appId: '1:631873486595:android:a9b562ed30554b6060f336',
    messagingSenderId: '631873486595',
    projectId: 'week1-firebas',
    storageBucket: 'week1-firebas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASy3Xd4Z5JtunaqRTceeywpakekWFkd1k',
    appId: '1:631873486595:ios:9805b9ce255da39360f336',
    messagingSenderId: '631873486595',
    projectId: 'week1-firebas',
    storageBucket: 'week1-firebas.firebasestorage.app',
    iosBundleId: 'com.example.week1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASy3Xd4Z5JtunaqRTceeywpakekWFkd1k',
    appId: '1:631873486595:ios:9805b9ce255da39360f336',
    messagingSenderId: '631873486595',
    projectId: 'week1-firebas',
    storageBucket: 'week1-firebas.firebasestorage.app',
    iosBundleId: 'com.example.week1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVM1BEEN3TX1fNkuJ_5qCwyhuKaC-NWpc',
    appId: '1:631873486595:web:89fbe8f71743d45f60f336',
    messagingSenderId: '631873486595',
    projectId: 'week1-firebas',
    authDomain: 'week1-firebas.firebaseapp.com',
    storageBucket: 'week1-firebas.firebasestorage.app',
    measurementId: 'G-7YMPC8KYE2',
  );
}
